### ISSUE TITLE
some more explanation on Shiny part

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/leaflet-in-R-lesson#11]
With the virtual teaching format and/or the possibility of self guided learners doing this lesson off the web, it might be nice to add a bit more text explaining what the code in the Shiny part of the lesson is doing. We could just link to relevant sections of the Shiny lesson if those would work to explain what's going on.

**Comment by andGarc** [comment]
I added more detailed text explaining the code. I also added more details and resources from the Shiny lesson on how to actually share a shiny app. In addition, I found the leafletproxy section to be missing a lot of content/details. I decided to remove the leafletproxy section. I don't think leafletproxy  is relevant here since the point of the shiny section is to get the reader to publish a map. leafletproxy opens a can of worms about app performance and improvement which in my option should be a separate lesson.

**Comment by andGarc** [comment]
I added a Shiny Optimization section that includes information on the leafletproxy function.
